import { writeFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { methodQuestion, TOPICS } from "./arithmetic";
import { fractionQuestion, FRACTION_TOPICS } from "./fractions";
import { FORMAT_LABEL, formatOf, inputOf, isRight, vary } from "./formats";
import { generators, KINDS, LEVELS, practiceSet, type Kind } from "./problems";
import { GRADES, makeQuestion, type Format, type Grade, type Question } from "./questions";
import { seeded, type Rng } from "./rng";
import { checkQuestion, render } from "./templates";
import { thinkingQuestion, THINKING_TOPICS } from "./thinking";

/** Every topic the way a child practices it: one maker per Play grade, skill, fractions topic, word/equation level and data & thinking topic. */
const PRACTICE: { id: string; grade: Grade; make: (r: Rng) => Question }[] = [
  ...GRADES.map((g) => ({ id: `play-grade-${g}`, grade: g, make: (r: Rng) => makeQuestion(g, r) })),
  ...TOPICS.map((t) => ({ id: t.id, grade: t.grade, make: (r: Rng) => methodQuestion(t, r) })),
  ...FRACTION_TOPICS.map((t) => ({ id: t.id, grade: t.grade, make: (r: Rng) => fractionQuestion(t, r) })),
  ...THINKING_TOPICS.map((t) => ({ id: t.id, grade: t.grade, make: (r: Rng) => thinkingQuestion(t, r) })),
  ...(Object.keys(KINDS) as Kind[]).flatMap((k) => LEVELS.map(({ id }) => ({ id: `${k}-${id}`, grade: generators(k, id)[0].grade, make: (r: Rng) => practiceSet(k, id, r, 1)[0] }))),
];
const DRAWS = 300;

function mix(make: (r: Rng) => Question, seed: number) {
  const r = seeded(seed), counts: Partial<Record<Format, number>> = {};
  for (let i = 0; i < DRAWS; i++) {
    const q = vary(make(r), r);
    const f = formatOf(q);
    counts[f] = (counts[f] ?? 0) + 1;
  }
  return counts;
}

const MIX = PRACTICE.map((p, i) => ({ ...p, counts: mix(p.make, i + 1) }));

describe("format coverage", () => {
  it.each(MIX.map((m) => [m.id, m] as const))("%s is asked in at least two formats, none more than 75% of the time", (_, m) => {
    const n = Object.values(m.counts);
    expect(n.length).toBeGreaterThanOrEqual(2);
    expect(Math.max(...n) / DRAWS).toBeLessThanOrEqual(0.75);
  });

  it.each(GRADES)("Play at grade %i mixes at least eight formats", (g) => {
    expect(Object.keys(MIX.find((m) => m.id === `play-grade-${g}`)!.counts).length).toBeGreaterThanOrEqual(8);
  });

  it.each(GRADES)("grade %i uses at least ten formats across its topics", (g) => {
    const all = new Set(MIX.filter((m) => m.grade === g).flatMap((m) => Object.keys(m.counts)));
    expect(all.size).toBeGreaterThanOrEqual(10);
  });

  it("every format is used somewhere", () => {
    const used = new Set(MIX.flatMap((m) => Object.keys(m.counts)));
    for (const f of Object.keys(FORMAT_LABEL)) expect(used, f).toContain(f);
  });

  // FORMAT_REPORT=docs/format-coverage.md npx vitest run src/lib/formats.test.ts
  it("writes the coverage table when asked", () => {
    const out = process.env.FORMAT_REPORT;
    if (!out) return;
    const formats = Object.keys(FORMAT_LABEL) as Format[];
    const pct = (m: (typeof MIX)[number], f: Format) => (m.counts[f] ? `${Math.round((m.counts[f]! / DRAWS) * 100)}%` : "");
    const rows = [...MIX].sort((a, b) => a.grade - b.grade).map((m) => `| ${m.grade} | ${m.id} | ${formats.map((f) => pct(m, f)).join(" | ")} |`);
    writeFileSync(out, [
      "# Question format mix per topic",
      "",
      `Share of ${DRAWS} practice questions per topic asked in each format. Generated by \`FORMAT_REPORT=docs/format-coverage.md npx vitest run src/lib/formats.test.ts\`.`,
      "",
      `| Grade | Topic | ${formats.map((f) => FORMAT_LABEL[f]).join(" | ")} |`,
      `|---|---|${formats.map(() => "---").join("|")}|`,
      ...rows,
      "",
    ].join("\n"));
  });
});

describe("formats", () => {
  it("every varied question is still valid", () => {
    for (const [i, p] of PRACTICE.entries()) {
      const r = seeded(1000 + i);
      for (let k = 0; k < 60; k++) {
        const q = vary(p.make(r), r);
        expect(checkQuestion(q, { negatives: true }), `${p.id}: ${q.text} ${q.ask ?? ""} :: ${q.choices.join(", ")}`).toEqual([]);
      }
    }
  });

  it("asks true or false with the real answer or a real mistake", () => {
    const r = seeded(3);
    let seen = 0;
    for (let i = 0; i < 500 && seen < 20; i++) {
      const q = vary(makeQuestion(4, r), r);
      if (q.format !== "truefalse") continue;
      seen++;
      expect(q.choices).toEqual(["True", "False"]);
      expect(q.ask).toMatch(/says the answer is .+\. True or false\?$/);
    }
    expect(seen).toBe(20);
  });

  it("finds the mistake from the template's own explanations", () => {
    const r = seeded(8);
    let seen = 0;
    for (let i = 0; i < 2000 && seen < 20; i++) {
      const base = makeQuestion(3, r), q = vary(base, r);
      if (q.format !== "mistake") continue;
      seen++;
      const shown = q.ask!.match(/got (.+)\. What mistake/)![1];
      const m = base.mistakes!.find((x) => x.answer === shown)!;
      expect(q.answer.toLowerCase()).toBe(m.why.toLowerCase());
    }
    expect(seen).toBe(20);
  });

  it("typed answers are matched by value", () => {
    const q: Question = { grade: 4, text: "x", std: "4.OA.A.3", answer: "$12", choices: [], format: "typein" };
    expect(isRight(q, "12")).toBe(true);
    expect(isRight(q, " $12.00 ")).toBe(true);
    expect(isRight(q, "13")).toBe(false);
    expect(isRight({ ...q, answer: "3/4" }, "6/8")).toBe(true);
    expect(isRight({ ...q, answer: "2 1/2" }, "2.5")).toBe(true);
    expect(isRight({ ...q, answer: "12 R 3" }, "12r3")).toBe(true);
    expect(isRight({ ...q, answer: "12 R 3" }, "12")).toBe(false);
    expect(isRight({ ...q, answer: "-7" }, "−7")).toBe(true);
  });

  it("order questions are answered by tapping the items in order", () => {
    const tpl = generators("word", "easy")[0];
    expect(inputOf(render(tpl, seeded(1)).question)).toBe("choose");
    const r = seeded(5);
    for (let i = 0; i < 200; i++) {
      const q = vary(makeQuestion(4, r, 12), r);
      expect(inputOf(q)).toBe("order");
      expect(isRight(q, q.answer)).toBe(true);
      expect(isRight(q, [...q.answer.split(", ")].reverse().join(", "))).toBe(false);
    }
  });
});
